### ISSUE TITLE
Changing stock_status via PUT rest api  is not possible

### ISSUE THREAD

**Issue by itsgauravjain22** [woocommerce/woocommerce-rest-api#114]
API  ->  PUT /wp-json/wc/v3/products/<id>

"stock_status" is not functional via put request. Tried changing from "instock" to "outofstock" and "onbackorder" of a simple product, but the output "stock_status" remain "instock"

**Comment by juliaamosova** [comment]
Hi @itsgauravjain22,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end when making a `PUT` request to update `stock_status` from `instock` to `outofstock`:

![stock](https://user-images.githubusercontent.com/19143190/73541243-d3717f00-4429-11ea-8f78-6682d730df81.jpg)

Please provide us with more details about the issue which may help us to evaluate it further. 

If you can share the exact request you make along with the body of the request, we can help identify what could be wrong.

**Comment by itsgauravjain22** [comment]
Kindly check this [link](https://www.screencast.com/t/7iN5GdcnYiOt) for details. I still have that problem.

**Comment by juliaamosova** [comment]
@itsgauravjain22 I am not able to open the link - is there any other way for you to share what you want to share?

**Comment by itsgauravjain22** [comment]
![1](https://user-images.githubusercontent.com/11793930/73560989-1e1ce680-447e-11ea-936d-cf55921cf28d.png)
![2](https://user-images.githubusercontent.com/11793930/73561018-2412c780-447e-11ea-9390-c7d9907c9126.png)

**Comment by itsgauravjain22** [comment]
It is not explicitly mentioned that stock_status field is dependent on present stock_quantity of a product anywhere in the document. I don't need to send `manage_stock` and `stock_quantity` along with `stock_status: out_of_stock`. There's undocumented server side check with these field. And I guess it's better to have it.

**Comment by ignacioinnovo** [comment]
I´m having the same issue. Could anyone tell me how do you resolve this issue? We need to send manage_stock and stock_quantity along with stock_status: out_of_stock? Since when? It was working well. Thank you in advanced!

**Comment by tepafril** [comment]
I'm having the same issue. trying to create with {."stock_status" : "instock" }. but result turned out to be "Out of Stock"

**Comment by ignacioinnovo** [comment]
Please, @itsgauravjain22 could you point us in the right direction? We are sending out_of_stock, manage_stock: "false" and stock_quantity=0 and the product stil shows in stock. Thank you very much in advanced!

**Comment by ignacioinnovo** [comment]
@tepafril Please, let me tell you that I´ve found the solution based on what @itsgauravjain22 posted. To set the product as in stock I sended: stock_status="in_stock", manage_stock="false" and stock_quantity=0. Then to set it as out of stock I sended: stock_status="out_of_stock", manage_stock="true" and stock_quantity=0.
