### ISSUE TITLE
Need a way to upload product image via file upload using Woocommerce Rest API

### ISSUE THREAD

**Issue by itsgauravjain22** [woocommerce/woocommerce-rest-api#123]
I can't find a way to upload local images for an existing product or a new product. The woocommerce PUT endpoint for ```/wp-json/wc/v3/products/<id>``` should have a way to upload image mechanism so that the external app could communicate with woocommerce store.
It should support the image data in Base64 with some checks on the server or any other suitable way to upload product images. This would be also really helpful for woocommerce mobile application being developing.
I read somewhere that its WordPress responsibility to handle product image. But that would make the process overly complicated as WordPress and woocommerce authentication mechanism for rest API are entirely different.

**Comment by itsgauravjain22** [comment]
Following the above discussion, I have referred WordPress [documentation](https://documenter.getpostman.com/view/8140651/SVYnQft9?version=latest#5eeb3cfc-89ae-4c3e-92b4-aef8586d1869) to upload media image and get image `source` from the response.

The problem with this mechanism is that the woocommerce rest API authentication keys can't validate the WordPress rest API. I kindly request the woocommerce team to develop rest endpoint for media uploads which are authenticated via woocommerce rest keys.

@claudiosanches  Could you help with this.

**Comment by itsgauravjain22** [comment]
Any update on this??? If someone could help to find the way to upload the product images via woocommerce rest api authenticated with consumer_key and consumer_secret

**Comment by juliaamosova** [comment]
Hi @itsgauravjain22,

Thank you for taking the time to share this idea, we really appreciate your help.

There is no other way to add an image to a product via WC REST API other than what you had already been doing. More on this here: https://github.com/woocommerce/woocommerce/issues/17556

Similar to your other requests, I am adding an `enhancement` label to it for now but we will need to evaluate this further with the WooCommerce Core team.

**Comment by itsgauravjain22** [comment]
Could this issue be prioritized. Would be great if woocommerce provide wrapper around wordpress media rest API authenticated with woocommerce keys/secret pair.

**Comment by victormattosvm** [comment]
@itsgauravjain22 have you tried Woocommerce Media API Plugin?

**Comment by claudiosanches** [comment]
> I read somewhere that its WordPress responsibility to handle product image. But that would make the process overly complicated as WordPress and woocommerce authentication mechanism for rest API are entirely different.

By default we disable our authentication method for other endpoints, but you can enable it using `woocommerce_rest_is_request_to_rest_api`.

With the Media REST API endpoint you can upload any image to WordPress, I recommend you using it before creating products and other objects.
Note that WooCommerce REST API is just a group of endpoints of the WordPress REST API, so it's all the same ecosystem, no reason to redo something that already exists ready in WordPress.
