### ISSUE TITLE
Include currency details in 'list all products' and 'retrieve a product' endpoints

### ISSUE THREAD

**Issue by itsgauravjain22** [woocommerce/woocommerce-rest-api#126]
Please include `currency`, `currency_symbol` and `currency_position` in the output of `GET /wp-json/wc/v3/products` and `GET /wp-json/wc/v3/products/<id>`

This would save calling `GET /wp-json/wc/v3/system_status` for every time the updated product data is required. Also, it would greatly enhance the usability of fetching product details via Rest API in the case of multi-currency stores.

**Comment by juliaamosova** [comment]
Hi @itsgauravjain22,

Thank you for taking the time to share this idea, we really appreciate your help.

Similar to your other requests, I am adding an `enhancement` label to it for now but we will need to evaluate this further with the WooCommerce Core team.

**Comment by seb86** [comment]
@itsgauravjain22 Is this required because you run a multi-currency store?

**Comment by itsgauravjain22** [comment]
@seb86 No, I am not using multi currency store currently. But the intention of creating this issue is to have multiple currency store. Also, it will make easier to display order currency in frontend if included in order details api response, instead of calling separate rest API just to fetch currency details.

**Comment by vedanshujain** [comment]
Supporting this out of the box is not possible because there is no currency property associated with the product. Multi-currency plugins can implement currency properties in different ways that WC core would not have any knowledge about so we can easily end up sending incorrect data. I am closing this issue but write back if I am missing something.

**Comment by Dipikesh** [comment]
I found a way to get currency here 
https://woocommerce.github.io/woocommerce-rest-api-docs/?javascript#list-all-system-status-items

In the response, there is field setting under that currency is present
