### ISSUE TITLE
Include 'dimension_unit' and 'weight_unit' in 'list all products' and 'retrieve a product' endpoints

### ISSUE THREAD

**Issue by itsgauravjain22** [woocommerce/woocommerce-rest-api#127]
Include `weight_unit` and `dimension_unit` in the output of `GET /wp-json/wc/v3/products` and `GET /wp-json/wc/v3/products/<id>`

`dimension_unit` should be a part of Dimension Object.

**Comment by juliaamosova** [comment]
Hi @itsgauravjain22,

Thank you for taking the time to share this idea, we really appreciate your help.

Similar to your other requests, I am adding an `enhancement` label to it for now but we will need to evaluate this further with the WooCommerce Core team.

**Comment by Jake-Convictional** [comment]
Currently trying to deal with this as well. These quantities aren't useful without the corresponding dimensions. Also not sure why `weight_unit` and `dimension_unit` aren't included in the `GET /` request, as [the docs](https://woocommerce.github.io/woocommerce-rest-api-docs/v1.html#endpoints) imply that they should be there.

It seems like the workaround to use for now is to call `OPTIONS /wp-json/v3/products` and parse the units from `schema.properties.weight.description` which looks like "Product weight (lbs).", and `schema.properties.dimensions.properties.[length|width|height].description` which looks like "Product length (in)." Link in the first paragraph lists possible values for these.

**Comment by vedanshujain** [comment]
Hi, unfortunately, we won't be adding dimension units in products API call because its technically not the property of the product, but of the entire store. You can get the exact unit with options from `/wp-json/wc/v3/settings/products` API call.
