### ISSUE TITLE
API authentication 401

### ISSUE THREAD

**Issue by RanNir143** [woocommerce/woocommerce-rest-api#128]
Hey, i have written an integration between my app and WooCommerce which allows users to sync their workflows on both platforms. I am using token based authentication as detailed the API(https://woocommerce.github.io/woocommerce-rest-api-docs/) to let users give me permissions to make API requests on their behalf.

some of my users receive 401 message when trying to give us permissions, without too many details in the message “Request failed with status code 401”
has anyone experienced something similar and has insights for help?

I made sure the user uses the correct consumer key and secret, and gives permissions of read/write.

**Comment by itsgauravjain22** [comment]
You haven't provided the complete details on how you provided tokens. Is it on http oauth token or https keys.
If it's http keys, I am unaware of this.
If it's https keys, there might be a problem with server trimming the Authentication headers. In that case, you can use username & password in url.

**Comment by liorke** [comment]
Hi @itsgauravjain22 , following up @ranyo2 question - YES, it is an https keys.
Can you describe better how exactly to use the consumer_key & consumer_secret to make it work?

this is how I use the api today, and it works only for HTTP urls:
```
 const client = new WooCommerceRestApi({
      url,
      consumerKey,
      consumerSecret,
      version: 'wc/v3'
    });
```

**Comment by itsgauravjain22** [comment]
I never used woocommerce rest client. But you can try hit the woocommrce rest API endpoint directly in postman.
For eg. 
Listing all products would be GET request to
`{{url}}/wp-json/wc/v3/products?page=1&per_page=20&consumer_key={{consumer_key}}&consumer_secret={{consumer_secret}}`

**Comment by liorke** [comment]
@itsgauravjain22 looks good, thanks!

**Comment by juliaamosova** [comment]
Hi @ranyo2, we apologize for the delayed response! Do you still need help with authentication? If so, can you please provide a bit more details on how exactly you authenticate right now?

**Comment by vedanshujain** [comment]
I am closing this issue as part of the repo maintenance, but feel free to comment back if this is not resolved. Thanks!
