### ISSUE TITLE
Push Notifications via Rest API

### ISSUE THREAD

**Issue by itsgauravjain22** [woocommerce/woocommerce-rest-api#129]
Need a way to trigger push notifications via rest API on various events like order status changed, order details modified, customer added, products update, product added.
It should be implemented for popular push notifications services in mind like firebase, onesignal, etc

**Comment by vedanshujain** [comment]
You can use [Webhook](https://docs.woocommerce.com/document/webhooks/) for this purpose, although it may require some customization to parse the response on the client-side.
