### ISSUE TITLE
Get count of all orders and by type

### ISSUE THREAD

**Issue by LocalHeroPro** [woocommerce/woocommerce-rest-api#133]
Please add endpoint to retrieve count of all - and by status type - orders.
Right now we can access to that data only after first fetch data from endpoint, using data hidden in header: X-WP-Total and X-WP-TotalPages.

**Comment by juliaamosova** [comment]
Hi @LocalHeroPro,

Thank you for taking the time to share this idea, we really appreciate your help. I am adding an `enhancement` label to your issue but we'd need to evaluate it further with the WooCommerce Core team.

**Comment by vedanshujain** [comment]
Hi, you can achieve this using [Retrieve orders total endpoint](https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-orders-totals). (also, apologies for late reply)
