### ISSUE TITLE
API Not return the public data

### ISSUE THREAD

**Issue by Ahhsan** [woocommerce/woocommerce-rest-api#141]
I’m making a mobile application for wooCommerce store, and for that I want that anyone should view my products, even he isn’t registered, like in my web. 
But when I make a request to get a list of products. It doesn’t returns and responds with error
{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}
Even thought my products are visible on my site to anyone.
what should I do ?
https://www.qmajd.com/wp-json/wc/v2/products

The page I need help with: http://qmajd.com

**Comment by seb86** [comment]
@Ahhsan My public products API is now available for early access to customers.

**Comment by Ahhsan** [comment]
how can I use it @seb86 ?

**Comment by seb86** [comment]
Probably best we continue the conversation via my live chat at CoCart.xyz

**Comment by vedanshujain** [comment]
Closing this issue as we don't yet support fetching products publicly from the API, and seems like conversation has been moved elsewhere.
