### ISSUE TITLE
regular_price can be a number instead of a string on /v3/products

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-rest-api#144]
If [Product Bundles](https://woocommerce.com/products/product-bundles/) is installed, bundle products will have a **number** as their `regular_price` in the `/wp-json/wc/v3/products` endpoint:

```json
  {
    "id": 10,
    "name": "Bundle",
    "type": "bundle",
    "status": "publish",
    "featured": false,
    "catalog_visibility": "visible",
    "price": 5,
    "regular_price": 5,
```

This contradicts the [REST API doc](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties) which mentions `regular_price` to be a `string`.

We expected the `regular_price` (and `price`) to have double quotes like this:

```json
  {
    "id": 10,
    "name": "Bundle",
    "type": "bundle",
    "status": "publish",
    "featured": false,
    "catalog_visibility": "visible",
    "price": "5",
    "regular_price": "5",
```

Here is a sample response showing `regular_price` to be returned as a number for bundled products but as a `string` for basic products: https://gist.github.com/shiki/c9f269eead51fa9c04a43e99a265810f

## Effect on the iOS app

For the [iOS app](https://github.com/woocommerce/woocommerce-ios), we rely on the API to return the correct data type. When the `regular_price` unexpectedly returned a number, the app failed to parse the response because of the mismatched types. This causes the app to fail to load the product list.

## Steps to Reproduce

I performed these steps on a fresh install of WordPress with WooCommerce.

1.  Installed and activated [WooCommerce Product Bundles](https://woocommerce.com/products/product-bundles/)
2. Created a product with these attributes:
    - Name: "Basic Product"
    - Type: Simple product
    - Regular Price: "18"

    All other properties are untouched.
3. Created a bundle product with these attributes:
    - Name: "Bundle"
    - Type: Product bundle
    - Regular price: 5

    Then, in the _Bundled Products_ section, add 2 bundled products:
    
    Product | Priced Individually 
    --------|-------
      Basic Product      |       ✔️
      Basic Product      |       ✔️

    The checked **Priced Individually** setting is important.
5. Execute GET /wp-json/wc/v3/products

## Notes

- If the Product Bundles extension is turned off, the `regular_price` will be `string`. 
- If the Product Bundles extension is on but the _Priced Individually_ setting is unchecked, the `regular_price` will be `string`. Though this seems to be inconsistent after a few times I tried editing the product.
---

### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.15
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.68.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.22-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: wp_
Total Database Size: 1.77MB
Database Data Size: 0.73MB
Database Index Size: 1.04MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 2
post: 2
product: 3
scheduled-action: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Jetpack by WordPress.com: by Automattic – 8.2.3
WooCommerce Product Bundles: by SomewhereWarm – 6.0.3
WooCommerce: by Automattic – 3.9.2

### Inactive Plugins (6) ###

AMP: by AMP Project Contributors – 1.4.4
CoBlocks: by GoDaddy – 1.21.1
Full Site Editing: by Automattic – 0.19
Gutenberg: by Gutenberg Team – 7.3.0
Layout Grid: by Automattic – 1.0.5
Page Optimize: by Automattic – 0.4.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Product Bundles ###

Database Version: 6.0.3
Template Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2020-02-25 23:37:24 +0000
Newest: 2020-02-25 23:37:24 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by seb86** [comment]
@shiki I suspect this is due to Product Bundles overrides the regular price value to which the REST API reads from so it's not enforcing the value type to remain the same. In my products API I wrap the value with the currency symbol.

I'm now wondering if I should provide a raw version as well.

**Comment by shiki** [comment]
Hi @seb86! This was fixed in the Product Bundles recently so it stopped happening. It was probably because of an override. Though I think the API itself should enforce this so that no other extensions could easily override the type.

> I'm now wondering if I should provide a raw version as well.

Sorry, I'm not familiar with your use case to give some advice. 🙂

**Comment by seb86** [comment]
@shiki Sorry I was referring to my [products API](https://cocart.xyz/add-ons/products/).

**Comment by vedanshujain** [comment]
Closing because this was handled in the mentioned extension. Overriding API fields is already a bit hard, so anyone overriding does know what they are doing. I would recommend to add another field in API instead of price, but that's something extension owner will take decision on.
