### ISSUE TITLE
Separate global rest API authentication plugin

### ISSUE THREAD

**Issue by itsgauravjain22** [woocommerce/woocommerce-rest-api#148]
I like the idea of basic authentication with strong key/secret pair for authenticating woocommerce rest API. But these keys can't authenticate other rest endpoints like WordPress rest API, dokan vendor API, wcfm multivendor rest API authentication.

I believe there should be standard authentication mechanism to authenticate users for store rest API in wordpress.

In current scenario, we need different authentication mechanism for woocommerce and wordpress endpoint. For eg. We can't upload a product image via woocommerce rest API authenticated with woocommerce keys as the wordpress rest API needs another authentication mechanism.

**Comment by juliaamosova** [comment]
Hi @itsgauravjain22,

Thank you for taking the time to share this idea, we really appreciate your help.

Similar to your other requests, I am adding an `enhancement` label to it for now but we will need to evaluate this further with the WooCommerce Core team.

**Comment by vedanshujain** [comment]
I am closing this issue since the WP core is planning on an [Application Password](https://make.wordpress.org/core/2020/09/23/proposal-rest-api-authentication-application-passwords/) approach. When it lands into the core, we will evaluate authenticating WC with it, which should solve this issue.
