### ISSUE TITLE
Creating product in batch with meta_data is not working

### ISSUE THREAD

**Issue by mujuonly** [woocommerce/woocommerce-rest-api#150]
```
$data = Array
    (
        [0] => Array
            (
                [name] => Mark
                [published] => 0
                [sku] => mark
                [regular_price] => 12
                [meta_data] => Array
                    (
                        [0] => Array
                            (
                                [key] => API
                                [value] => using REST
                            )

                        [1] => Array
                            (
                                [key] => Test M
                                [value] => TST
                            )

                    )

            )

        [1] => Array
            (
                [name] => Mark – II
                [published] => 0
                [sku] => Mark-ii
                [regular_price] => 4
                [meta_data] => Array
                    (
                        [0] => Array
                            (
                                [key] => API
                                [value] => using REST ii
                            )

                        [1] => Array
                            (
                                [key] => Test M
                                [value] => TST ii
                            )

                    )

            )

    )

print_r( $store_client->post( 'products/batch', ['create' => $data ] ) );
```

Any issue with the data format.?

[https://stackoverflow.com/q/60631396/1117368](https://stackoverflow.com/q/60631396/1117368)

**Comment by stefanos82** [comment]
Your problem seems to be the actual data you are passing inside your `meta_data`. If those data don't exist, won't work.

Now, what do I mean by that; let's say you have extended your `functions.php` or you have created a custom plugin that extends WooCommerce by adding a unit quantity that let users measure their stock in kilograms and you gave it the meta data value id `_unit_quantity`.

That `_unit_quantity` should be your `[key]` and for `[value]` whatever you have originally saved in with your custom function or plugin.

**Comment by mujuonly** [comment]
@stefanos82  I think your understanding is wrong. am talking about custom metadata - not the hidden metadata.

**Comment by stefanos82** [comment]
Well, you weren't clear at all in your postings.

Good luck.

**Comment by mujuonly** [comment]
@stefanos82  My sample data itself describes it's custom  metadata. Thanks though

**Comment by vedanshujain** [comment]
I was able to create a product using the API and the data that you mention in the issue. Are you still facing this problem? I am closing the issue as part of general maintainence, but feel free to comment back if you are still facing an issue, along with details like WooCommerce version, exact response data, error details (if any) etc to help us debug.
