### ISSUE TITLE
how do i filter resources by the date modified? the after parameter provided only filters by date created

### ISSUE THREAD

**Issue by aman2505** [woocommerce/woocommerce-rest-api#153]
We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
 from a human being - submit a ticket via the helpdesk
https://woocommerce.com/contact-us/ 

**General usage and development questions**
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The WooCommerce Help and Share Facebook group

**Comment by vedanshujain** [comment]
You can use `column` parameter along with `after` to filter on modified, for example:

`wc/v3/products?consumer_key=xxxx&cs_secret=xxxx&after=2020-09-30T10:06:59&column=modified`
