### ISSUE TITLE
Ability to select list of GET request without authentication

### ISSUE THREAD

**Issue by itsgauravjain22** [woocommerce/woocommerce-rest-api#154]
The woocommerce rest API are cool but they have very limited purpose. Just modify the store with mobile or ther app.

I think this pupose can be further enhanced to use the rest API in general if there's ability to select some GET endpoints to be used in consumer application. That would open the doors for front-end mobile apps, modern spa web apps like https://www.vuestorefront.io/

Also it will open channels to market to create pwa storefronts and mobile apps  based on woocommerce as backend.

I think woocommerce is very much behind the other opensource solutions present in market in this modern architecture. I am not complaining the devs, just presenting my opinion. Anyone can extend woocommerce, but would be better if it comes with the official platform itself. Checkout saleor, spree and vendure projects. They're really cool projects considering their modern architecture.

**Comment by seb86** [comment]
@itsgauravjain22 CoCart has an add-on that provides the products without authentication. https://cocart.xyz/add-ons/products/

**Comment by vedanshujain** [comment]
@itsgauravjain22 Thanks for the enhancement request, this is something we are evaluating, but at this point, I don't think we can say if or when we would develop/release this feature in WC core. That said, do keep an eye on our [development block](https://developer.woocommerce.com/) in case we do release similar feature.
