### ISSUE TITLE
"Invalid parameter(s): after, before on List all products API

### ISSUE THREAD

**Issue by itsgauravjain22** [woocommerce/woocommerce-rest-api#164]
As per [documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products) of `GET{{url}}/wp-json/wc/v3/products?consumer_key={{consumer_key}}&consumer_secret={{consumer_secret}}&after=2019-04-01&before=2020-04-01`, I got the following error:

```
{
    "code": "rest_invalid_param",
    "message": "Invalid parameter(s): after, before",
    "data": {
        "status": 400,
        "params": {
            "after": "Invalid date.",
            "before": "Invalid date."
        }
    }
}
```

As the dates included in the URL are ISO8601 compliant, it might be the bug.

**Comment by davidprifti** [comment]
That is not the correct format that is needed. The correct ISO8601 format is like this 2020-09-28T09:32:32 where you have to add the time as well.

**Comment by vedanshujain** [comment]
Closing as part of general repo maintainence. The response above should solve the issue, correct format also includes time.
