### ISSUE TITLE
API V3 - How to retrieve Order details by order number instead of id?

### ISSUE THREAD

**Issue by iqoOopi** [woocommerce/woocommerce-rest-api#165]
API V3 - How to retrieve Order details by order number instead of id?

**Comment by itsgauravjain22** [comment]
I believe order number is same as order id in woocommerce. Please give more details of which order number you're talking about.

**Comment by iqoOopi** [comment]
> I believe order number is same as order id in woocommerce. Please give more details of which order number you're talking about.

Hey, there
Order Id and number are 2 different property. 
![image](https://user-images.githubusercontent.com/46897552/78950050-cc4e9900-7a8a-11ea-969e-1c040d1e7fa0.png)

**Comment by iqoOopi** [comment]
In most time, we use order number in daily business as it is customlizable.

**Comment by itsgauravjain22** [comment]
Ok, that's a major improvement and woocommerce team should look into it. But I'm really confused that I don't see changing order numbers in the admin panel. Is it a custom plugin you used to change the order number.

Screenshots:
[https://nimb.ws/pnyDS9](https://nimb.ws/juXdYO)
[https://nimb.ws/pnyDS9](https://nimb.ws/pnyDS9)

**Comment by negapo** [comment]
Order number is not part of the REST API, you can check the order properties here [https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties](url)
That "number" field is being added probably by a plug-in. A dirty trcik would be to append to the "number" the "id" so the number would look like "DF-4498-190504" and then just parse out the latest part to get the order.

**Comment by vedanshujain** [comment]
Closing this issue as part of general maintainence. As reponses states above, the order number is not part of standard API and is likely added by a plugin, so we won't be able to support filtering on this parameter in core.
