### ISSUE TITLE
Woocommerce Products added via Frontend Page - Sort Price Issue

### ISSUE THREAD

**Issue by kynello** [woocommerce/woocommerce-rest-api#169]
Hello, 
i can't solve this issue with Woocommerce.

I'm using a Frontend Page to add new products in a simple way (for a shop manager).
Every new product is correctly added but doesn't respect the sort price display (from the lowest to the highest, or vice versa).

So, for example, if the display product order is from the lowest to the highest price, the product added by frontend is displayed as the first. 

I noticed that it's an issue related to Table Products Order of Woocommerce.
So to solve the issue i need (every time i add a new product via frontend page) to go under Woocommerce > Status > Tools > Restore Table Products Order.

The Frontend page Add New Product has been made with Booster for Woocommerce Plugin.

**Comment by vedanshujain** [comment]
Hi there,
Apologies for the late reply on this, but looks like this is not a WooCommerce core functionality and therefore won't be able to provide support for the issue. Perhaps asking in the [Booster for Woocommerce Plugin's support forums](https://wordpress.org/plugins/woocommerce-jetpack/) will be a better idea.
