### ISSUE TITLE
Product tax class should return tax class object in get product properties

### ISSUE THREAD

**Issue by itsgauravjain22** [woocommerce/woocommerce-rest-api#170]
The `GET /wp-json/wc/v3/products/<id>` and `GET /wp-json/wc/v3/products` should output selected tax class object instead of only string, containing slug and name. This would prevent calling `GET /wp-json/wc/v3/taxes/classes` repeatedly when fetching product details.

The selected tax object should be similar to the output of `GET /wp-json/wc/v3/taxes/classes` and formatted as product categories object. For eg.
```
{
    "slug": "standard",
    "name": "Standard Rate"
}
```

**Comment by vedanshujain** [comment]
Fetching the name of the class needs a database call, and so we won't be able to implement this enhancement anytime soon.  The reasoning behind it is that generally a store will have very few tax classes and will be updated very rarely, and therefore it's feasible to make a call once to List all classes endpoint (/wp-json/wc/v3/taxes/classes) and store them on the client side for referencing and getting the full name.
I am closing the issue but feel free to comment back if you'd like to discuss more.
