### ISSUE TITLE
Addin gtin with woocommerce rest api

### ISSUE THREAD

**Issue by cipi79** [woocommerce/woocommerce-rest-api#172]
Hi,

I have install Product Feed PRO for WooCommerce plugin which enables gtin field for my products. 
In the product edit page I can update or insert this field.

How to do the same with the woocommerce rest api? 

I have tried to send meta_data with json but no success?
“meta_data”:[{“value”:”xxxxxxxxxxxxxx”,”key”:”_woosea_gtin”}]

**Comment by vedanshujain** [comment]
The data format that you specify should work, and will correctly add the metadata for the product (assuming this is wrapped properly in a JSON body with a product ID). We won't be able to help further as this is a custom plugin and the actual plugin authors of Product Feed PRO will have better expertise to answer and confirm if that's what you need to do to add gtin field for your products.
