### ISSUE TITLE
Rest API - Order by price

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce-rest-api#174]
**Is your feature request related to a problem? Please describe.**
Sort products by price high / low should be possible from the Rest API for headless sites and services. This is a very common feature for most sites..

**Describe the solution you'd like**
Order products using rest api by price high / low

**Describe alternatives you've considered**
Writing a plugin is the only alternative, but that should not be necessary.

**Additional context**
This was said to be added in Rest API v3, but I can still not find it. Ref.  https://github.com/woocommerce/woocommerce/issues/16215#issue-244629748

**Comment by vedanshujain** [comment]
With API V3, we do support sorting by price, use the API like so `wp-json/wc/v3/products?orderby=price&order=desc`. Note that in case of variable or grouped product, we will take variation with max price when sort order is DESC and min price when sort order is ASC.
