### ISSUE TITLE
Adding Image through ID not working

### ISSUE THREAD

**Issue by andrewchanlg** [woocommerce/woocommerce-rest-api#175]
Hi all, I'm trying to add an image to my product through PUT /wp-json/wc/v3/products/792?. Image ID for 403 exist in media gallery
Payload:
{
        "images":[
          {
            "ID":403,
            "position":0
          }
        ]
        }
I kept getting this error:
{
    "code": "woocommerce_product_invalid_image_id",
    "message": "#0 is an invalid image ID.",
    "data": {
        "status": 400
    }
}

**Comment by vedanshujain** [comment]
Looks like there are a couple of issues with the API request:
`ID` should be `id`
`position` arguement is not supported.

So the payload should be:
```json
{
  "images": [
		{
			"id": 403
		}
	]
}
```
(I realise that its pretty late and you would have moved on from this issue, but answering in case someone else face the same problem and lands up on this issue.)
