### ISSUE TITLE
Delete custom fees from order

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce-rest-api#178]
It is not possible to remove **fee_line** for orders using the API.

For the **line_items** it is possible to set **quantity** to **0** or **product_id** to **null**, but that is not possible with **fee_lines**. I tried to set the whole value of **fee_lines** to null which did not remove anything and also changing total of order to 0 & remove name did not work.

**Endpoint:** wp-json/wc/v3/orders/632
**Method:** PUT
**Data:**
```json
{
 "fee_lines": [{ "id": "743", "name": "I cannot be deleted :-/", "total": 0 }],
 "line_items": [{ "id": "362", "name": "I can be deleted! :-)", "quantity": 0}]
}
```

**Comment by vedanshujain** [comment]
You can remove a fee line by setting the name to `null` like so in a PUT request:
```json
{
  "fee_lines": [
		{ "id": 743, "name": null }
	]
}
```
Thanks for raising the issue, we are adding this into documentation to make this more clearer https://github.com/woocommerce/woocommerce-rest-api-docs/pull/181

**Comment by ienzam** [comment]
Doesn't seem to work. I get the error:
```
{"code":"woocommerce_rest_invalid_fee_item","message":"Fee name is required.","data":{"status":400}}
```

The following lines do not allow null:

https://github.com/woocommerce/woocommerce-rest-api/blob/88ff745b300488d9d2145fa1ab73a2715558530a/src/Controllers/Version2/class-wc-rest-orders-v2-controller.php#L723

https://github.com/woocommerce/woocommerce-rest-api/blob/88ff745b300488d9d2145fa1ab73a2715558530a/src/Controllers/Version4/Requests/OrderRequest.php#L260

**Comment by kumarmanishc** [comment]
@vedanshujain I confirm that this is working with wc/v1

`But this is giving Internal server Error if we use v3`
