### ISSUE TITLE
Add prices include tax to system_status endpoint

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce-rest-api#179]
**Endpoint**: wp-json/wc/v3/system_status

Can you please add **prices_include_tax** to settings or environment?

It would be really helpful for POS systems using the Rest API.

**Comment by vedanshujain** [comment]
This setting is available in settings endpoint in `wp-json/wc/v3/settings/tax/` under id `woocommerce_prices_include_tax`
