### ISSUE TITLE
One product no longer returning order results

### ISSUE THREAD

**Issue by edpankau** [woocommerce/woocommerce-rest-api#182]
For 2 years, I've been using something along the lines of `https://warneravenueelementary.com/wp-json/wc/v2/orders?product=1307&status=completed&after=2019-08-10T00:00:00&orderby=date&order=asc` to retrieve orders for product 1307. Recently, however, that query returns no orders, which is incorrect. Other similar products (e.g., 1370) return orders just fine. Please help!

**Comment by vedanshujain** [comment]
Hi, there is no recent change in product functionality as far as I can see, and unfortunately there are not enough details for us to try to reproduce the issue. Generally, for help like these, support forums are a better place as you will get an early response there. I am closing this issue as part of general repo maintainence, but please open another issue in [WooCommerce core repo](https://github.com/woocommerce/woocommerce) if you are still able to repro this.
