### ISSUE TITLE
Create a new product with new variations through API

### ISSUE THREAD

**Issue by fernando-worked** [woocommerce/woocommerce-rest-api#189]
Hello guys, I already check the docs, but no found a corret way to do that.

`{
   "name":"Produto criado via API",
   "sku":"via-api",
   "type":"variable",
   "description":"Um novo produto criado via api",
   "short_description":"Criado API",
   "attributes":[
      {
         "id":"2",
         "slug":"cor",
         "name":"Cor",
         "options":["A definir"],
				 "visible":true,
				 "variation":true
      }
   ],
   "variations":[
      {
         "regular_price":"25.00",
         "attributes":[
            {
               "id":"2",
               "option":"A definir"
            }
         ]
      }
   ]
}`

This is my code.
Url post in: https://website/wp-json/wc/v3/products

Expected result: Insert a product with 1 variation with predefined attributes. Those ids are correct. Both product and variations are new.

Actual results: A product beggin correctly inserted with attribute "Cor", but none of its variations.

**Comment by fernando-worked** [comment]
> Hi @fernando-worked,
> 
> Thank you for reporting the issue. WooCommerce REST API is being developed in another repository: https://github.com/woocommerce/woocommerce-rest-api.
> 
> I am going to move your bug report there so that we could take a look further there.

Ok, thank you! I still looking futher for a solution!

**Comment by fernando-worked** [comment]
Guys, I need help in this question, somebody please?

tried this `{
   "create":[
      {
         "name":"criado via api",
         "type":"variable",
         "regular_price":"25.00",
         "attributes":[
            {
               "id":"2",
               "slug":"cor",
               "name":"Cor",
               "options":[
                  "A definir"
               ],
               "visible":true,
               "variation":true
            }
         ],
         "variations":[
            {
               "regular_price":"25.95",
               "attributes":[
                  {
                     "id":"2",
                     "option":"A definir"
                  }
               ]
            }
         ]
      }
   ]
}`

new end-point: wp-json/wc/v3/products/batch

**Comment by vedanshujain** [comment]
Created product, as well as its variation, is not supported as of now as per docs. So basically you would have to divide your request across two API calls, [one for the product](https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-product) and [other for the variation](https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-product-variation), after fetching the product id of the newly created product. 

IDs are pregenerated and read only, so you won't be able to specify them in an API call for creating the resource. 

Note that generally support forums are better places to ask these type of question, as you may get reply sooner. We use github for bug tracking and fixing.
