### ISSUE TITLE
Retrieve customer returns response code 200 even with no customer

### ISSUE THREAD

**Issue by hicreate** [woocommerce/woocommerce-rest-api#197]
Hi,

Is there any way to add a 404 response code for not found customers? At present if I make a GET request to find a specific customer it returns 200 with an empty data property on the response, whilst I believe better practice would be to return a 404 for alignment with data validation practices.

Thanks

**Comment by HammerOz** [comment]
This is the same for a product. I agree

**Comment by vedanshujain** [comment]
Thanks for the enhancement request, however, returning 200 when no customer is found is actually inline with industry-standard REST API specifications. We would return 404 when the endpoint itself does not exist, for example, if we would not support listing customers at all and the endpoint didn't exist at all, only in that case 404 would have been appropriate. Also changing this behavior will be backward incompatible, so unfortunately we won't be able to implement this suggestion.
