### ISSUE TITLE
[Question]: Rest API store object filter

### ISSUE THREAD

**Issue by ayazzz** [woocommerce/woocommerce-rest-api#198]
Hello,
I am trying to help a client of mine to pull orders data via rest api.
They have 1 site for 4 different brands. Each store has it's id and some information related to the store.
As you can see in the screenshot, the orders endpoint returns regular data and "store" information as well.

Is there a way to filter the orders by stores on API call?
I already tried with query strings like "store.id=11" or "store_id=11" or "store=11" but it didn't work..

![wc-api-orders-store](https://user-images.githubusercontent.com/10224424/82708969-2b382e00-9c45-11ea-85b3-a8d091b92dbf.PNG)

Thanks a lot in advance!!

**Comment by helgatheviking** [comment]
@ayazzz While not an expert in the API, I think you can filter the object query here:
https://github.com/woocommerce/woocommerce-rest-api/blob/6e146038e11327324a7e8dc94fd204063868a24e/src/Controllers/Version3/class-wc-rest-crud-controller.php#L314

**Comment by vedanshujain** [comment]
Looks like `store` is a custom data provided by an external plugin, so we won't be able to implement the search functionality for it in the core code. Perhaps you would need to raise this enhancement request with the plugin authors that add this functionality>
