### ISSUE TITLE
Getting error `rest_invalid_param` when updating quantity with decimals

### ISSUE THREAD

**Issue by Codeia** [woocommerce/woocommerce-rest-api#199]
This issue doesn't seem to have any official discussion. I'm building a React JS app to process orders from WooCommerce using the official REST API. After I process the order I send the following payload:

`{ product_id: 122, quantity: 0.5 }`

But this results with the following error:

`line_items[1][quantity] is not of type integer.`

Not really sure how to proceed from here, I found nothing on the internet. Some help is super appreciated.

**Comment by Codeia** [comment]
Looking at the API Docs, it seem that `quantity` is expected to be `integer`.
Working for the past 2 weeks hardcore, on an app which now can never be alive. Great lol

**Comment by vyrzdev** [comment]
There's a functions.php patch for it, I am using it now, if you can't find it on google reply and I'll send you it.

You just have to override the model with one where it's expected as decimal.

:)

**Comment by vedanshujain** [comment]
This request can be solved by customizations or by external plugins, but we don't have any plans to support decimal values for quantity in core yet. @vyrzdev it will be helpful to share a patch if you have it ready with everyone so that whoever needs it can get it :) .

**Comment by DenilsonSparkLabs** [comment]
@vyrzdev Podrías comentarme cual fue la solución?

**Comment by vyrzdev** [comment]
I do not have a patch, and this was long ago my apologies - but I remember
finding a plugin for WooCommerce which did enable decimal quantities. To
get this to work with the API I essentially just followed the requests
through until I found the conditional with this error, and removed it- it
seemed to work just fine with the quantity updating correctly.

Sorry I don't have more, I no longer am working with the store in question.
