### ISSUE TITLE
many “images” will cause same SKU product

### ISSUE THREAD

**Issue by hqin2013** [woocommerce/woocommerce-rest-api#200]
Hey,

I found a problem when using WC-rest-API.

when creating a variable product, if this product has **many images in "images" field** ( these images are creating very low), then Woocommerce  will generate more than one product  -- **with **same SKU****

any suggestion?!

Regards
Qin

**Comment by vedanshujain** [comment]
I was not able to reproduce the issue on my end, I tried creating a variable product with multiple images, but as expected only one product was created. 

I am closing this issue as part of general housekeeping of the repo, but if you are facing this error, can you please open another issue in [WooCommerce core repo](https://github.com/woocommerce/woocommerce) with following details:
1. [System status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/)
2. Exact request URL and reponse with payload data (after hiding authentication details and any other sensitive data as needed.)
