### ISSUE TITLE
Customer.GetAll is not returning all customers

### ISSUE THREAD

**Issue by TolchinJ** [woocommerce/woocommerce-rest-api#208]
When I call Customer.GetAll, I get a whole lot of customers.  Then I do an Order.GetAll and import those.  But when I check the Customer ID from Orders against the Customer ID from Customers, I have a lot that are missing.  When I enter a specific customer Id that is missing, they come up. (e.g. wc.Customer.Get(CustomerID))
likewise, without the wrapper:
https://www.url.com/wp-json/wc/v3/customers  (lots, but missing some (like woocommerce/woocommerce#202))
https://www.url.com/wp-json/wc/v3/customers/202 (finds the customer)

**Comment by vedanshujain** [comment]
As mentioned in the above comment by @Soufiane21, by default the results are paginated and you will only get the first 10 results. Please use a loop to read through all the pages to get all customers. Depending upon your client, there could be a method called `getHeaders` which will return an object containing a field `x-wp-totalpages` indicating the total number of pages you would need to loop through.

Closing this repo as part of general maintenance. If you are still seeing this issue please report back with exact request and response data (after removing any sensitive information), api client you are using and a [system status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/).
