### ISSUE TITLE
knowing if a category has subcategories or product

### ISSUE THREAD

**Issue by federicotortora** [woocommerce/woocommerce-rest-api#209]
is there a way to know if a category has subcategories or has a product directly under it without getting all the products from that category first?

**Comment by cipiloosh** [comment]
You can check if there are any categories with parent.

```  {
    "id": 15,
    "name": "Albums",
    "slug": "albums",
    "parent": 11,
    "description": "",
    "display": "default",
    "image": [],
    "menu_order": 0,
    "count": 4,
 } ```
So this is a subcategory for the category with the id = 11.

**Comment by vedanshujain** [comment]
To see if there are products for a category, check the `count` field in the category response. If there are products it will be greater than 0. 

To see if there are subcategories for a category, use the `parent` query param. For example, if you want to check if a category with ID 314 has subcategoriesa or not, make the request like so: `/wp-json/wc/v3/products/categories/?parent=314`. If the response is empty array, it means there no subcategories and vice versa.
