### ISSUE TITLE
Woocomerce API - Does't return all the categories

### ISSUE THREAD

**Issue by cipiloosh** [woocommerce/woocommerce-rest-api#211]
Hi,
I use woocommerce-rest-api and and I have a problem when I'm trying to get the categories.

const categories = await api.get("products/categories");

It returns only some categories, not all the categories.

Any ideea? 
Thanks!

**Comment by vedanshujain** [comment]
This is possibly the same as #208 , so paraphrasing by response here:

> by default the results are paginated and you will only get the first 10 results. Please use a loop to read through all the pages to get all customers. Depending upon your client, there could be a method called `getHeaders` which will return an object containing a field `x-wp-totalpages` indicating the total number of pages you would need to loop through.

In your case, this should be the same for categories, basically, results are paginated and we need to loop through pages to get all of them. I am closing this issue but feel free to comment if there are additional questions.
