### ISSUE TITLE
REST API: Delete All the variations

### ISSUE THREAD

**Issue by tahafarooqui** [woocommerce/woocommerce-rest-api#215]
This idea has been discussed since 5 years but unfortunately this feature is still not available.  Is it possible to use **all**  or any other parameter to delete all variants using rest API.

```
WooCommerce.delete("products/22/variations/all", {
  force: true
})
  .then((response) => {
    console.log(response.data);
  })
  .catch((error) => {
    console.log(error.response.data);
  });
```

**Comment by vedanshujain** [comment]
Unfortunately, at this time this is not possible, the closest workaround is to use the batch delete endpoint which can be used to 100 variations at a time.

I am closing this issue as we won't be able to prioritize it soon-ish, and I think when we do pick it up, we can add endpoints for all the variation bulk actions that we support, and not just delete all.
