### ISSUE TITLE
Unable to do refunds on per line item basis via RESP API.

### ISSUE THREAD

**Issue by mnaeem76** [woocommerce/woocommerce-rest-api#216]
When creating refunds from within WooCommerce , the refund line items represent itemized refunds giving a snapshot how much quantity, amount and tax was refunded. However, the REST API does not seem to support this. The documentation shows only a lump-sum amount can be refunded. 

Is there a way itemized refunds can be created using the REST API as well? If not are there any future plans to support this feature? I'm working on a project where WooCommerce platform is used for store front-end and the back office is integrated/managed via custom .net C# applications due to integration requirements with customer's existing ERP system. Everything is working fine except for doing itemized refunds via API. 

I'm seeing posts here that people are struggling with creating such refunds via API so I find their workarounds quite inconclusive.  If any light can be shed on this matter with a temporary workaround or future enhancements plan will be highly appreciated.

**Comment by vedanshujain** [comment]
We are planning to support this soon, but I am closing this issue since we will track this enhancement in https://github.com/woocommerce/woocommerce/issues/27566.
