### ISSUE TITLE
low_stock_amount attribute

### ISSUE THREAD

**Issue by DarkxNess** [woocommerce/woocommerce-rest-api#218]
i need help with the Low stock threshold parametters, is he available in the woo api?

**Comment by vedanshujain** [comment]
Yes, its available at `/wc/v3/settings/products/woocommerce_notify_low_stock_amount` endpoint. Also, be sure to explore whole of `/wc/v3/settings/products/` and `/wc/v3/settings/` to see what all settings modifications we support.
