### ISSUE TITLE
[API] Get Customer has totally different attributes then before

### ISSUE THREAD

**Issue by NicoJuicy** [woocommerce/woocommerce-rest-api#22]
Endpoint : https://shop/wp-json/wc/v4/customers?search=first_name

I receive the following model:
 
    [  
    {  
      "id":x,
      "user_id":1,
      "username":"NicoJuicy",
      "name":"Nico Sap",
      "email":"email",
      "country":"BE",
      "city":"some-villa",
      "state":"",
      "postcode":"number-zipcode",
      "date_registered":"2016-05-31T00:45:02",
      "date_last_active":"-0001-11-30T00:00:00",
      "orders_count":2,
      "total_spend":0,
      "avg_order_value":0,
      "date_last_order":"2017-12-05 22:09:15",
      "date_registered_gmt":"2016-05-30T23:45:02",
      "date_last_active_gmt":"-0001-11-30T00:00:00",
      "_links":{  
         "customer":[  
            {  
               "href":"https:\/\/www.shop\/wp-json\/wc\/v4\/customers\/1"
            }
         ]
      }
    }]
    
Which is extremely weird. I also can't navigate to /wp-json/wc/v4/customers/1

v2 end v3 endpoints give the expected model ( with first_name and last_name).

I'm on version 3.7 and wanted to use v4 endpoint, because i had results when searching for a "guest" name.

I didn't have that match on v2/v3.

Is it possible to advise me on what endpoint i should lookup a guest account based on first_name and last_name? 

Use-case: looking up orders based on first_name, last_name and email, when  a client sends me an email ( can be from another mail).

**Comment by rrennick** [comment]
@NicoJuicy Thanks for reporting this. Based on some testing this looks like it's an issue with the WooCommerce Admin plugin. I created https://github.com/woocommerce/woocommerce-admin/issues/2781.

Do you have the `woocommerce-rest-api` plugin installed and active?

**Comment by juliaamosova** [comment]
Hi @NicoJuicy, the issue had been resolved in https://github.com/woocommerce/woocommerce-admin/pull/3174. Can you please test and let us know if it works as expected on your end?

**Comment by vedanshujain** [comment]
Closing this as part of repository maintainence, but feel free to post back if there are any additional comments.
