### ISSUE TITLE
REST API /wc/store/cart* endpoint documentation needed - Headless WooCommerce

### ISSUE THREAD

**Issue by thd-fox** [woocommerce/woocommerce-rest-api#220]
I searched for a long time on the internet and also here in the existing issues.
Though I found nothing about the cart rest endpoint.
I'm going to build a headless WooCommerce client.
I'm running against various errors that I need to get rid of by reverse engineering the woocommerce code.

I found a plugin that provides a payed solution but I don't want to rely on it as there are obvious bugs found.

**Describe the solution you'd like**
I'd love to see the endpoint /wc/store/cart* documented in the woo rest api documentation

**Comment by thd-fox** [comment]
@juliaamosova as you can see there is in fact a reachable cart endpoint:
```
curl -X POST "https://domain.tld/wp-json/wc/store/cart/add-item?consumer_key=ck_aaaaaaaaaaaaaaaaaaa&consumer_secret=cs_bbbbbbbbbbbbbbbb"
-H "accept: application/json" 
-H "authorization: Basic xxxxxxxxxxxxxxxxxx" 
-H "Content-Type: application/x-www-form-urlencoded" 
-H "_wpnonce: xxxxxxxxx" 
-d "id=9999999&quantity=1"
```
which gives me the following answer:
```
{
   "code":"woocommerce_rest_missing_nonce",
   "message":"X-WC-Store-API-Nonce-Header missing. This endpoint requires a valid Nonce.",
   "data":{
     "status":401
   }
}
```
I suppose you use it for gutenberg blocks. I'd need to know the right nonce header name.
If one could just document this endpoint as is already exists would be awesome :)

**Comment by peterfabian** [comment]
Hi, 

the store API is being developed by the Blocks team in https://github.com/woocommerce/woocommerce-gutenberg-products-block. As it's currently under development for Cart and Checkout, it's not stable yet, and thus not entirely public, and not documented yet. If you want to check how to use it, please have a look at Cart and Checkout blocks. 

However, once we reach maturity with the API, we plan to open it up and document it as the rest of the REST API.

**Comment by timohausmann** [comment]
> I'd need to know the right nonce header name.

The header name is `X-WC-Store-API-Nonce` and the nounce name is `wc_store_api`.
I got the endpoint talking, but it doesn't add items to the cart. Would be nice to have in the future.

**Comment by timohausmann** [comment]
> I'd need to know the right nonce header name.

The header name is `X-WC-Store-API-Nonce` and the nounce name is `wc_store_api`.

I got it working, make sure to add a product/variant id and a quantity. PHP+JS example with `wp_create_nonce`:

```
<script>
var _nonce = "<?php echo wp_create_nonce( 'wc_store_api' ); ?>";
$.ajax({
  type: 'POST',
  url: '/wp-json/wc/store/cart/add-item',
  dataType: 'json',
  headers: {
    'X-WC-Store-API-Nonce': _nonce
  },
  data: {
    id : 378,
    quantity: 1
  }
});
</script>
```

**Comment by thedarkcder** [comment]
Is it possible to attach the cart to an existing customer? I'm trying to update the cart from another platform as an admin user

**Comment by mohit-rzy** [comment]
@thd-fox Did you get the cart api working for a headless scenario?

**Comment by thd-fox** [comment]
@mohit242 we are now back into headless development and you can see extended cart endpoint here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/trunk/src/StoreApi
This seems promising :)

**Comment by apoorvHearth** [comment]
@thd-fox how are you maintaining the cart per user, as per my testing the cart value is not changing even if I am logging in with multiple users. The cart is shared amongst all of them.

**Comment by baijumelepura** [comment]
Hi,
how can I add multiple products to  Cart for a customer?
/wc/store/cart* 
Rest Api

**Comment by wpscreatros** [comment]
Hi,
How can we add a variable product using postman as when I use the endpoint
/wc/store/cart/add-item?id=13914&quantity=5
id 13914 is a variation of the product 13911 it adds the product 13914 however in the json response the variation attributes are missing 
any idea on how to pass the data in API requests?

**Comment by peterfabian** [comment]
Hi @wpscreatros (and others) please raise similar questions in the repository for Blocks where this gets developed until it gets merged to core: https://github.com/woocommerce/woocommerce-gutenberg-products-block.

As for this particular question, please check [the relevant documentation in GH](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/docs/cart.md#add-item). If it doesn't work, please open an issue in [the Blocks repository](https://github.com/woocommerce/woocommerce-gutenberg-products-block). thanks.

**Comment by tahseengds** [comment]
These old end end points are no longer available, does anyone know about new endpoints and there documentations.

**Comment by rajan281197** [comment]
@tehseengds ,
I am also looking for the add to cart,login,registration end point if someone has idea about that then let me know so that would be helpful.

**Comment by yochaiglik-epalle** [comment]
+1 looking for a wc endpoints to add, remove, etc products from cart

**Comment by peterfabian** [comment]
Please check the new location for Store API documentation: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/README.md
