### ISSUE TITLE
Modify WC_REST_Products_V2_Controller->prepare_object_for_database()

### ISSUE THREAD

**Issue by pixelschupser** [woocommerce/woocommerce-rest-api#222]
Heyo,

is there a way to modify "WC_REST_Products_V2_Controller->prepare_object_for_database()" because i have to change the way it identifies the "Product categories".

**Comment by vedanshujain** [comment]
You can use the filter `woocommerce_rest_pre_insert_product_object`, which will be called at the end of this method (so basically before product is saved to DB) and you can use it to do any modifications.

I am closing the issue as part of repo maintainence, but feel free to comment back if you have more questions.
