### ISSUE TITLE
return 401

### ISSUE THREAD

**Issue by sbc640964** [woocommerce/woocommerce-rest-api#233]
I do what appears in these tutorials
https://docs.woocommerce.com/document/woocommerce-rest-api/
https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

i sent the keys on the headers or on params
and still return 401.

I check at three sites and everyone return 401

What about it?

**Comment by vedanshujain** [comment]
If you are still facing this problem then can you please open another issue in [WooCommerce core repo](https://github.com/woocommerce/woocommerce) after filling out the issue template (click on the new issue there, and you will see the template)? There is very little information in the issue description to provide any meaningful help.
