### ISSUE TITLE
Authenticating against WooCommerce API with customer usernamer/Password

### ISSUE THREAD

**Issue by ThiagoFazzi** [woocommerce/woocommerce-rest-api#236]
We are re-building an Easy Order Wordpress plugin with VueJs, that uses WooCommerce REST API.

Current flow: The customer go to the website and do a login with email/password, with the login done, the user can go to 'Easy Order' link to access the plugin and then the user get all products categories, subcategories and products. the user can add/remove products into his cart.

What we are trying to reach: We are changing the plugin to use the WooCommerce REST API, but there is no way to access the data with a customer email/password login in WooCommerce REST API, the Wordpress login does not work at all with WooCommerce REST API.

How can I get access with customer credentials to the Woocommerce REST API?

Thanks in advanced.

**Comment by vedanshujain** [comment]
So WooCommerce API is designed for admin access only and isn't really suited to be directly accessed by customers. There are 3PD plugins however that can allow you to do that.

That said, if you do want to go ahead in this direction, then I can suggest two workflows:

1. Generate consumer_key and consumer_secret pair for the customer with read access when they sign in using [authentication endpoint](https://woocommerce.github.io/woocommerce-rest-api-docs/?javascript#rest-api-keys), see `/wc-auth/v1/authorize`.

2. Add custom code in your plugin to hook into `woocommerce_api_check_authentication` filter and authenticate users depending upon your logic.

I hope this answer was helpful, I am closing this issue as part of repo maintainence, but if you have further questions or enhancement to suggest to better support these kinds of workflows, please open another issue in our [core repo](https://github.com/woocommerce/woocommerce) (we are going to deprecate this particular repo soon, as API code is now merged into core).
