### ISSUE TITLE
Fixing compatibility had broken API requests

### ISSUE THREAD

**Issue by ksholomov** [woocommerce/woocommerce-rest-api#237]
https://github.com/woocommerce/woocommerce-rest-api/commit/efd2e62c63903661fc9f5f932bfb99f19ff8f822
You had changed validation rules from mixed to nullable string and my app stopped working. Before that commit integers and arrays were accepted. Why do you change so important logic?? It took me 5 hours to find that problem code!

**Comment by redelschaap** [comment]
I see also issues with the latest version of WooCommerce and its API.

For sites that use WooCommerce 4.3.2 with API package version 1.0.10, we can't update the sales price dates anymore. We get the following response:

```
Invalid parameter(s): date_on_sale_from, date_on_sale_to [rest_invalid_param]
```

**Comment by vedanshujain** [comment]
This is being tracked and fixed in https://github.com/woocommerce/woocommerce/issues/27282 . We are planning a fix release this week to address the issue.
