### ISSUE TITLE
Add endpoint to request total product count for the parameters provided

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-rest-api#25]
On woo-mobile, we have a need to show the total count of products so we don't have to download all products just to give the user a total count. This endpoint should support all the same properties as the products list endpoint so we can query for a count of products by various filters such as type, status, category, on_sale...etc.

**Comment by glutaminefree** [comment]
Total products count returned in **X-WP-Total** header. [See on StackExchange](https://wordpress.stackexchange.com/questions/217490/get-post-count-in-wp-rest-api-v2-and-get-all-categories/274198)

**Comment by vedanshujain** [comment]
Closing as per the response of @glutaminefree . Feel free to write back if that header does not work.

**Comment by Devendra0110** [comment]
Shouldn't this be mentioned in docs?
:confused:
