### ISSUE TITLE
Return URL gets striped of all query parameters except the 1st one

### ISSUE THREAD

**Issue by abishekrsrikaanth** [woocommerce/woocommerce-rest-api#34]
Since this issue is pertaining to the `return_url` through the REST API, I am also creating this issue here as it affects both repositories.

Issue: https://github.com/woocommerce/woocommerce/issues/24685

**Comment by claudiosanches** [comment]
See my comment in https://github.com/woocommerce/woocommerce/issues/24685#issuecomment-537622214
