### ISSUE TITLE
Not possible to delete meta_data from REST APi

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce-rest-api#75]
Currently its not possible to delete meta_data from rest api, for example like this:
```

$update['meta_data'][] = [
    'key' => "my_meta_data",
    'value' => ""
];
print_r($woocommerce->put('orders/727', $update));
```

'my_meta_data' will still be there. even when I do this to delete all meta_data:

```
$update['meta_data'] = array();`
print_r($woocommerce->put('orders/727', $update));
```

Its also not possible.

**Comment by vedanshujain** [comment]
Hi @erikdemarco , apologies for the late reply. I guess you would have moved on by now from this problem, but for any future readers, metadata can be deleted by passing null in the meta vlaue like so:
```php
$update['meta_data'][] = [
    'key' => "my_meta_data",
    'value' => null
];
print_r($woocommerce->put('orders/727', $update));
```

**Comment by larssn** [comment]
For future readers: the above does NOT delete the meta data entry. It only sets the value to null.
