### ISSUE TITLE
Products Controller: images property type should be array not object

### ISSUE THREAD

**Issue by om4james** [woocommerce/woocommerce-rest-api#76]
The [REST API v1 defines the "images" property](https://github.com/woocommerce/woocommerce-rest-api/blob/master/src/Controllers/Version1/class-wc-rest-products-v1-controller.php#L2149) with a type of object (which is incorrect).
The [REST API v2 defines the "images" property](https://github.com/woocommerce/woocommerce-rest-api/blob/master/src/Controllers/Version2/class-wc-rest-products-v2-controller.php#L1917) with a type of array (correct).
The [REST API v3 defines the "images" property](https://github.com/woocommerce/woocommerce-rest-api/blob/master/src/Controllers/Version3/class-wc-rest-products-controller.php#L1125) with a type of object (incorrect).

A product can have multiple images, so the type should be array.

Can this be fixed in [V4](https://github.com/woocommerce/woocommerce-rest-api/blob/master/src/Controllers/Version4/Products.php#L497) so that the type is correctly defined as an array?

I did a quick audit of all type: object definitions in the V3 controllers and this property is the only one that I could see that is incorrect.

Thank you.

**Comment by juliaamosova** [comment]
Closing as it is fixed in https://github.com/woocommerce/woocommerce-rest-api/pull/86.
