### ISSUE TITLE
Adjust Woocommerce Order Search (OR instead of AND)

### ISSUE THREAD

**Issue by younesberg** [woocommerce/woocommerce-rest-api#78]
I need the adjustment, that one can enter more than only one order-ID into the search and get accordingly several orders.

For example “12002 12003 12004”, so that you get these 3 orders listed.

Does anyone know which line(s) of code must be adjusted, so that the search function uses OR instead of AND? Or ss there a plugin for that?

Many thanks in advance!

**Comment by weaselmetal** [comment]
See:
http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders

The `include` parameter should be the filter you are looking for, according to the documentation.

**Comment by vedanshujain** [comment]
Closing as above comment correctly answers the questions.
