### ISSUE TITLE
Problem with detach category from product

### ISSUE THREAD

**Issue by vaniok010** [woocommerce/woocommerce-rest-api#8]
How can I detach a category from a product?

Why such a request does not work?

PUT /wp-json/wc/v3/products/39037

{  
   “categories”:[  
      {  
         “id”:1239
      },
      {  
         “id”:1232
      }
   ]
}

Why do I continue to get the old categories?

“categories”:[  
   {  
      “id”:1096,
      “name”:“Кроссовки”,
      “slug”:“sneaker”
   },
   {  
      “id”:1239,
      “name”:“Носки”,
      “slug”:“clothing-socken”
   },
   {  
      “id”:1232,
      “name”:“Одежда”,
      “slug”:“clothing”
   },
   {  
      “id”:1233,
      “name”:“Шапки”,
      “slug”:“clothing-caps”
   }
]

How can I leave only categories 1239, 1232 and remove the rest?

**Comment by vaniok010** [comment]
![image](https://user-images.githubusercontent.com/6134702/62195938-ba5a1980-b385-11e9-9a00-d1aa1c91bb21.png)

**Comment by vedanshujain** [comment]
I am cleaning up this repository issues happened upon this issue, apologies for the year late reply.

As far as I can see you are using the correct syntax and its working for me in my local testing, so I am guessing something else might have been an issue (perhaps a plugin conflict?). I am closing the issue but feel free to write back if you have additional comments.
