### ISSUE TITLE
Getting Tag by Name as well as ID

### ISSUE THREAD

**Issue by Lirian21** [woocommerce/woocommerce-rest-api#83]
I was wondering

If this is a feature? and how it works. 

Then if it's not is that something that can be Considered to be added?

My Reasoning for this.

So in my application for instance I have main "Categories" but instead of using a 

Category -> Sub Cat -> Sub cat 

Kind of approach I used Tags as the Main so:

Tags -> Category - > Sub cat.

Now I use those tags in "Flash Sale's" Or Notification's to Pass threw Custom Product list's to build Temporary Shop's of sort. So for me it's Not the thing best having to add a INT to a push Notification I'd much rather prefer working with the Name of the Tag.

**Comment by juliaamosova** [comment]
Hi @Lirian21,

Thank you for raising the issue!

If I understand you correctly, you should be able to retrieve a product tag and manipulate it further as per documentation below:

https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-product-tag

Please let me know if this is not what you are looking for?

**Comment by Lirian21** [comment]
Hi Sorry for the late response, 

I'm Explaining this Poorly, In the most simple of terms, Currently I have a Push Notification that Delivers a ID of a Product Group Then I take that ID to Display that Product group Under a Special Sales Page.

So my Notification currently looks like this

[Image](https://imgur.com/RRbEoi1v)

So you can see Its weird having a Number as a title, So I was curious weather Product Tag names could be used to call instead. 

So it would read:

ABE instead of the number If that make's sense

**Comment by juliaamosova** [comment]
Sounds like a plan @Lirian21! 

I am going to close this issue as it seems your question had been resolved.
