### ISSUE TITLE
Display all variation attributes in orders endpoint

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce-rest-api#9]
Currently not possible to get all attributes without an addition request.

**Comment by AmandaRiu** [comment]
If already modifying the order detail API endpoint response, would it be possible to include the following updates to the `line_items` for the mobile app? (See p91TBi-2Lt-p2)
- The base name of the product purchased (no selected selected attributes appended)
- Update the selected attributes in `meta_data` to include the attribute label to display
- The product image URL for loading the thumbnail (of a variation - then the appropriate variation url)

**Comment by shiki** [comment]
Hi @claudiosanches! I'm gonna take a crack at this. 

Do you have some quick pointers? 🙂

**Comment by vedanshujain** [comment]
Closing since https://github.com/woocommerce/woocommerce/pull/27492 is now merged
