### ISSUE TITLE
Sold out.

### ISSUE THREAD

**Issue by Vliesie** [woocommerce/woocommerce-rest-api#97]
I was wondering if the Api Returns Item's that are out of stock, And weather this is Intentional

So I would have a Product Group Called Let's Say Paint, 2/4 Paints would be sold out on the site They will not appear when the stock is out,

However on the api They appear still, And i'm curious if there's any plans for the Api to handle "Checks" On Checkouts for Quantity of Checkout item -> Site Item Quantity 

And then give a Response we can then handle, So if you checkout a Paint Brush at a Quantity of 20 and the site has 15 On The Order.Add Response If there could be a check on that Response.I've looked threw and cant seem to find anything about this, So not sure if i'm missing something.

**Comment by juliaamosova** [comment]
Hi @Vliesie,

We have a product property called `stock_status` which controls the stock status of the product. I believe this s what you are looking for. Options are: `instock`, `outofstock`, `onbackorder`. Default is `instock`:

https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

You can manipulate it to create conditions and results you need.

**Comment by Vliesie** [comment]
Hey @juliaamosova

Hmmm I have tried with stock status the issue I was facing was that I don't have a big enough Test group, As its me mySelf and I, If I give you a Scenario Can you maybe Confirm weather this would work or not? Also Please Consider adding a 0 to any Number of Customers I provide 

Okay so:

I have a Product Called Eggs There are currently 50 of them, And I have 3 Customers With them in there Cart's, I have a Function that checks for the status before the items are added to the line orders, Now Customer A Keeps Browsing Customer B Purchases 40 Egg's Customer C Attempt's to Purchase 20 at the Same time Currently In that function it also pulls all Products and Compares StockQ before Completing, Now It notifies Customer C that There is only 10 Left, During this time Customer A has purchased the last 10 Egg's This all Happening within around maybe 30 Seconds, Is the Status of that Item going to Be updated in that time So I can notify Customer C that the Product is now Sold out

As for my first Question I have Tag A with 5 Products E.g Now 3 out of the 5 Products of A are sold out, On the Site if I visit Tag A it only shows 2 Products, However on the API side of things Tag A still displays the 5 Products. This is Intentional correct? 

I do Apologize if i'm overlooking something simple or repeating myself, This is my First ever API i've worked with.

**Comment by vedanshujain** [comment]
If the customer has purchased the item then the quantity will be reduced in real-time. Tag API shows the published product with that tag, whether out of stock or not. So I would say you should use the Product endpoint instead of the tag endpoint to get more realtime data.
(I am closing the issue since its pretty stale, but feel free to write back and we will reopen it.)

**Comment by Vliesie** [comment]
Almost 6 months to respond to a "stale" question and frankly your response is stale :)  u can close this. Again I've long ago found ways around this horrid api
